[package]
name = "example-basic"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
axum = "0.6"
tokio = { version = "1", features = ["full"] }
hyro = { path = "../../" }
tower-http = "0.4"
