[package]
name = "example-basic"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
axum = "0.6"
tokio = { version = "1", features = ["full"] }
hyro = { path = "../../", features = ["framework-axum"] }
tower-http = { version = "0.4", default-features = false, features = ["fs"] }
